<script src='{{ asset("upturn/js/jquery-3.2.1.min.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/bootstrap.min.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/plugins.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/jquery.magnific-popup.min.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/owl.carousel.min.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/jquery.ajaxchimp.min.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/jquery.waypoints.min.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/isotope.pkgd.min.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/scrollax.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/TweenLite.min.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/jquery.themepunch.revolution.min.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/extensions/revolution.extension.slideanims.min.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/extensions/revolution.extension.layeranimation.min.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/extensions/revolution.extension.navigation.min.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/extensions/revolution.extension.parallax.min.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/jquery.easypiechart.min.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/delighters.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/slick.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/main.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/custom.js") }}' charset="utf-8"></script>
<script src='{{ asset("upturn/js/form.js") }}' charset="utf-8"></script>
